import React, { useState } from 'react';
import './DsaPractice.css';

const DSAPractice = () => {
  const [activeTopic, setActiveTopic] = useState("Array");
  const [searchQuery, setSearchQuery] = useState("");
  
  const questionsData = {
   Array: [
                    { question: "Reverse the array", link: "https://www.geeksforgeeks.org/write-a-program-to-reverse-an-array-or-string/" },
                    { question: "Find the maximum and minimum element in an array", link: "https://www.geeksforgeeks.org/maximum-and-minimum-in-an-array/" },
                    { question: 'Find the "Kth" max and min element of an array', link: "https://www.geeksforgeeks.org/kth-smallestlargest-element-unsorted-array/" },
                    { question: "Given an array which consists of only 0, 1 and 2. Sort the array without using any sorting algo", link: "https://www.geeksforgeeks.org/sort-an-array-of-0s-1s-and-2s/" },
                    { question: "Move all the negative elements to one side of the array", link: "https://www.geeksforgeeks.org/move-negative-numbers-beginning-positive-end-constant-extra-space/" },
                    { question: "Find the Union and Intersection of the two sorted arrays.", link: "https://www.geeksforgeeks.org/union-and-intersection-of-two-sorted-arrays-2/" },
                    { question: "Write a program to cyclically rotate an array by one.", link: "https://www.geeksforgeeks.org/c-program-cyclically-rotate-array-one/" },
                    { question: "find Largest sum contiguous Subarray [V. IMP]", link: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/" },
                    { question: "Minimise the maximum difference between heights [V.IMP]", link: "https://www.geeksforgeeks.org/minimize-the-maximum-difference-between-the-heights/" },
                    { question: "Minimum no. of Jumps to reach end of an array", link: "https://www.geeksforgeeks.org/minimum-number-of-jumps-to-reach-end-of-a-given-array/" },
                    { question: "find duplicate in an array of N+1 Integers", link: "https://www.geeksforgeeks.org/find-duplicates-in-on-time-and-constant-extra-space/" },
                    { question: "Merge 2 sorted arrays without using Extra space.", link: "https://www.geeksforgeeks.org/merge-two-sorted-arrays-o1-extra-space/" },
                    { question: "Kadane's Algo [V.V.V.V.V IMP]", link: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/" },
                    { question: "Merge Intervals", link: "https://www.geeksforgeeks.org/merging-intervals/" },
                    { question: "Next Permutation", link: "https://www.geeksforgeeks.org/next-permutation/" },
                    { question: "Count Inversion", link: "https://www.geeksforgeeks.org/counting-inversions/" },
                    { question: "Best time to buy and Sell stock", link: "https://www.geeksforgeeks.org/stock-buy-sell/" },
                    { question: "find all pairs on integer array whose sum is equal to given number", link: "https://www.geeksforgeeks.org/given-an-array-a-and-a-number-x-check-for-pair-in-a-with-sum-as-x/" },
                    { question: "find common elements In 3 sorted arrays", link: "https://www.geeksforgeeks.org/find-common-elements-three-sorted-arrays/" },
                    { question: "Rearrange the array in alternating positive and negative items with O(1) extra space", link: "https://www.geeksforgeeks.org/rearrange-array-alternating-positive-negative-items-o1-extra-space/" },
                    { question: "Find if there is any subarray with sum equal to 0", link: "https://www.geeksforgeeks.org/find-if-there-is-a-subarray-with-0-sum/" },
                    { question: "Find factorial of a large number", link: "https://www.geeksforgeeks.org/factorial-large-number/" },
                    { question: "find maximum product subarray", link: "https://www.geeksforgeeks.org/maximum-product-subarray/" },
                    { question: "Find longest consecutive subsequence", link: "https://www.geeksforgeeks.org/longest-consecutive-subsequence/" },
                    {
                        question: 'Given an array of size n and a number k, find all elements that appear more than "n/k" times.',
                        link: "https://www.geeksforgeeks.org/given-an-array-of-of-size-n-finds-all-the-elements-that-appear-more-than-nk-times/",
                    },
                    { question: "Maximum profit by buying and selling a share at most twice", link: "https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-twice/" },
                    { question: "Find whether an array is a subset of another array", link: "https://www.geeksforgeeks.org/find-whether-an-array-is-subset-of-another-array-set-1/" },
                    { question: "Find the triplet that sum to a given value", link: "https://www.geeksforgeeks.org/find-a-triplet-that-sum-to-a-given-value/" },
                    { question: "Trapping Rain water problem", link: "https://www.geeksforgeeks.org/trapping-rain-water/" },
                    { question: "Chocolate Distribution problem", link: "https://www.geeksforgeeks.org/chocolate-distribution-problem/" },
                    { question: "Smallest Subarray with sum greater than a given value", link: "https://www.geeksforgeeks.org/minimum-length-subarray-sum-greater-given-value/" },
                    { question: "Three way partitioning of an array around a given value", link: "https://www.geeksforgeeks.org/three-way-partitioning-of-an-array-around-a-given-range/" },
                    { question: "Minimum swaps required bring elements less equal K together", link: "https://www.geeksforgeeks.org/minimum-swaps-required-bring-elements-less-equal-k-together/" },
                    { question: "Minimum no. of operations required to make an array palindrome", link: "https://www.geeksforgeeks.org/minimum-number-of-merges-to-make-array-palindrome/" },
                    { question: "Median of 2 sorted arrays of equal size", link: "https://www.geeksforgeeks.org/median-of-two-sorted-arrays/" },
                    { question: "Median of 2 sorted arrays of different size", link: "https://www.geeksforgeeks.org/median-of-two-sorted-arrays-of-different-sizes/" },
                ],
                Matrix: [
                    { question: "Spiral traversal on a Matrix", link: "https://www.geeksforgeeks.org/print-a-given-matrix-in-spiral-form/" },
                    { question: "Search an element in a matrix", link: "https://www.geeksforgeeks.org/search-in-row-wise-and-column-wise-sorted-matrix/" },
                    { question: "Find median in a row wise sorted matrix", link: "https://www.geeksforgeeks.org/find-median-row-wise-sorted-matrix/" },
                    { question: "Find row with maximum no. of 1's", link: "https://www.geeksforgeeks.org/find-the-row-with-maximum-number-1s/" },
                    { question: "Print elements in sorted order using row-column wise sorted matrix", link: "https://www.geeksforgeeks.org/print-elements-sorted-order-row-column-wise-sorted-matrix/" },
                    { question: "Maximum size rectangle", link: "https://www.geeksforgeeks.org/maximum-size-rectangle-binary-sub-matrix-1s/" },
                    { question: "Find a specific pair in matrix", link: "https://www.geeksforgeeks.org/find-a-specific-pair-in-matrix/" },
                    { question: "Rotate matrix by 90 degrees", link: "https://www.geeksforgeeks.org/rotate-a-matrix-by-90-degree-in-clockwise-direction-without-using-any-extra-space/" },
                    { question: "Kth smallest element in a row-column wise sorted matrix", link: "https://www.geeksforgeeks.org/kth-smallest-element-in-a-row-wise-and-column-wise-sorted-2d-array-set-1/" },
                    { question: "Common elements in all rows of a given matrix", link: "https://www.geeksforgeeks.org/common-elements-in-all-rows-of-a-given-matrix/" },
                ],
                String: [
                    { question: "Reverse a String", link: "https://www.geeksforgeeks.org/reverse-a-string-in-c-cpp-different-methods/" },
                    { question: "Check whether a String is Palindrome or not", link: "https://www.geeksforgeeks.org/c-program-check-given-string-palindrome/" },
                    { question: "Find Duplicate characters in a string", link: "https://www.geeksforgeeks.org/print-all-the-duplicates-in-the-input-string/" },
                    { question: "Why strings are immutable in Java?", link: "https://www.geeksforgeeks.org/why-string-is-immutable-in-java/" },
                    { question: "Write a Code to check whether one string is a rotation of another", link: "https://www.geeksforgeeks.org/a-program-to-check-if-strings-are-rotations-of-each-other/" },
                    { question: "Write a Program to check whether a string is a valid shuffle of two strings or not", link: "https://www.geeksforgeeks.org/check-whether-a-given-string-is-an-interleaving-of-two-other-given-strings/" },
                    { question: "Count and Say problem", link: "https://www.geeksforgeeks.org/count-and-say-sequence/" },
                    { question: "Write a program to find the longest Palindrome in a string.[ Longest palindromic Substring]", link: "https://www.geeksforgeeks.org/longest-palindrome-substring-set-1/" },
                    { question: "Find Longest Recurring Subsequence in String", link: "https://www.geeksforgeeks.org/longest-repeating-subsequence/" },
                    { question: "Print all Subsequences of a string.", link: "https://www.geeksforgeeks.org/print-subsequences-string/" },
                    { question: "Print all the permutations of the given string", link: "https://www.geeksforgeeks.org/write-a-c-program-to-print-all-permutations-of-a-given-string/" },
                    { question: "Split the Binary string into two substring with equal 0s and 1s", link: "https://www.geeksforgeeks.org/split-the-binary-string-into-substrings-with-equal-number-of-0s-and-1s/" },
                    { question: "Word Wrap Problem [VERY IMP].", link: "https://www.geeksforgeeks.org/word-wrap-problem-dp-19/" },
                    { question: "EDIT Distance [Very Imp]", link: "https://www.geeksforgeeks.org/edit-distance-dp-5/" },
                    { question: "Find next greater number with same set of digits. [Very Very IMP]", link: "https://www.geeksforgeeks.org/find-next-greater-number-set-digits/" },
                    { question: "Balanced Parenthesis problem.[Imp]", link: "https://www.geeksforgeeks.org/check-for-balanced-parentheses-in-an-expression/" },
                    { question: "Word break Problem[ Very Imp]", link: "https://www.geeksforgeeks.org/word-break-problem-dp-32/" },
                    { question: "Rabin Karp Algo", link: "https://www.geeksforgeeks.org/rabin-karp-algorithm-for-pattern-searching/" },
                    { question: "KMP Algo", link: "https://www.geeksforgeeks.org/kmp-algorithm-for-pattern-searching/" },
                    { question: "Convert a Sentence into its equivalent mobile numeric keypad sequence.", link: "https://www.geeksforgeeks.org/convert-sentence-equivalent-mobile-numeric-keypad-sequence/" },
                    { question: "Minimum number of bracket reversals needed to make an expression balanced.", link: "https://www.geeksforgeeks.org/minimum-number-of-bracket-reversals-needed-to-make-an-expression-balanced/" },
                    { question: "Count All Palindromic Subsequence in a given String.", link: "https://www.geeksforgeeks.org/count-palindromic-subsequence-given-string/" },
                    { question: "Count of number of given string in 2D character array", link: "https://www.geeksforgeeks.org/find-count-number-given-string-present-2d-character-array/" },
                    { question: "Search a Word in a 2D Grid of characters.", link: "https://www.geeksforgeeks.org/search-a-word-in-a-2d-grid-of-characters/" },
                    { question: "Boyer Moore Algorithm for Pattern Searching.", link: "https://www.geeksforgeeks.org/boyer-moore-algorithm-for-pattern-searching/" },
                    { question: "Converting Roman Numerals to Decimal", link: "https://www.geeksforgeeks.org/converting-roman-numerals-decimal-lying-1-3999/" },
                    { question: "Longest Common Prefix", link: "https://www.geeksforgeeks.org/longest-common-prefix-using-sorting/" },
                    { question: "Number of flips to make binary string alternate", link: "https://www.geeksforgeeks.org/number-flips-make-binary-string-alternate/" },
                    { question: "Find the first repeated word in string.", link: "https://www.geeksforgeeks.org/find-first-repeated-word-string/" },
                    { question: "Minimum number of swaps for bracket balancing.", link: "https://www.geeksforgeeks.org/minimum-swaps-bracket-balancing/" },
                    { question: "Find the longest common subsequence between two strings.", link: "https://www.geeksforgeeks.org/longest-common-subsequence-dp-4/" },
                    { question: "Program to generate all possible valid IP addresses from given string.", link: "https://www.geeksforgeeks.org/program-generate-possible-valid-ip-addresses-given-string/" },
                    { question: "Write a program to find the smallest window that contains all characters of string itself.", link: "https://www.geeksforgeeks.org/smallest-window-contains-characters-string/" },
                    { question: "Rearrange characters in a string such that no two adjacent are same", link: "https://www.geeksforgeeks.org/rearrange-characters-string-no-two-adjacent/" },
                    { question: "Minimum characters to be added at front to make string palindrome", link: "https://www.geeksforgeeks.org/minimum-characters-added-front-make-string-palindrome/" },
                    { question: "Given a sequence of words, print all anagrams together", link: "https://www.geeksforgeeks.org/given-a-sequence-of-words-print-all-anagrams-together/" },
                    { question: "Find the smallest window in a string containing all characters of another string", link: "https://www.geeksforgeeks.org/find-the-smallest-window-in-a-string-containing-all-characters-of-another-string/" },
                    { question: "Recursively remove all adjacent duplicates", link: "https://www.geeksforgeeks.org/recursively-remove-adjacent-duplicates-given-string/" },
                    { question: "String matching where one string contains wildcard characters", link: "https://www.geeksforgeeks.org/wildcard-character-matching/" },
                    { question: "Function to find Number of customers who could not get a computer", link: "https://www.geeksforgeeks.org/function-to-find-number-of-customers-who-could-not-get-a-computer/" },
                    { question: "Transform One String to Another using Minimum Number of Given Operation", link: "https://www.geeksforgeeks.org/transform-one-string-to-another-using-minimum-number-of-given-operation/" },
                    { question: "Check if two given strings are isomorphic to each other", link: "https://www.geeksforgeeks.org/check-if-two-given-strings-are-isomorphic-to-each-other/" },
                    { question: "Recursively print all sentences that can be formed from list of word lists", link: "https://www.geeksforgeeks.org/recursively-print-all-sentences-that-can-be-formed-from-list-of-word-lists/" },
                ],
                "Searching & Sorting": [
                    { question: "Find first and last positions of an element in a sorted array", link: "https://www.geeksforgeeks.org/find-first-and-last-positions-of-an-element-in-a-sorted-array/" },
                    { question: "Find a Fixed Point (Value equal to index) in a given array", link: "https://www.geeksforgeeks.org/find-a-fixed-point-in-a-given-array/" },
                    { question: "Search in a rotated sorted array", link: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/" },
                    { question: "square root of an integer", link: "https://www.geeksforgeeks.org/square-root-of-an-integer/" },
                    { question: "Maximum and minimum of an array using minimum number of comparisons", link: "https://www.geeksforgeeks.org/maximum-and-minimum-in-an-array/" },
                    { question: "Optimum location of point to minimize total distance", link: "https://www.geeksforgeeks.org/optimum-location-point-minimize-total-distance/" },
                    { question: "Find the repeating and the missing", link: "https://www.geeksforgeeks.org/find-a-repeating-and-a-missing-number/" },
                    { question: "find majority element", link: "https://www.geeksforgeeks.org/majority-element/" },
                    { question: "Searching in an array where adjacent differ by at most k", link: "https://www.geeksforgeeks.org/searching-array-adjacent-differ-k/" },
                    { question: "find a pair with a given difference", link: "https://www.geeksforgeeks.org/find-a-pair-with-the-given-difference/" },
                    { question: "find four elements that sum to a given value", link: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/" },
                    { question: "maximum sum such that no 2 elements are adjacent", link: "https://www.geeksforgeeks.org/maximum-sum-such-that-no-two-elements-are-adjacent/" },
                    { question: "Count triplet with sum smaller than a given value", link: "https://www.geeksforgeeks.org/count-triplets-with-sum-smaller-that-a-given-value/" },
                    { question: "merge 2 sorted arrays", link: "https://www.geeksforgeeks.org/merge-two-sorted-arrays/" },
                    { question: "print all subarrays with 0 sum", link: "https://www.geeksforgeeks.org/print-all-subarrays-with-0-sum/" },
                    { question: "Product array Puzzle", link: "https://www.geeksforgeeks.org/product-array-puzzle/" },
                    { question: "Sort array according to count of set bits", link: "https://www.geeksforgeeks.org/sort-array-according-count-set-bits/" },
                    { question: "minimum no. of swaps required to sort the array", link: "https://www.geeksforgeeks.org/minimum-number-swaps-required-sort-array/" },
                    { question: "Bishu and Soldiers", link: "https://www.geeksforgeeks.org/bishu-soldiers/" },
                    { question: "Rasta and Kheshtak", link: "https://www.geeksforgeeks.org/rasta-and-kheshtak/" },
                    { question: "Kth smallest number again", link: "https://www.geeksforgeeks.org/kth-smallest-number-again/" },
                    { question: "Find pivot element in a sorted array", link: "https://www.geeksforgeeks.org/find-pivot-element-sorted-rotated-array/" },
                    { question: "K-th Element of Two Sorted Arrays", link: "https://www.geeksforgeeks.org/k-th-element-two-sorted-arrays/" },
                    { question: "Aggressive cows", link: "https://www.geeksforgeeks.org/aggressive-cows/" },
                    { question: "Book Allocation Problem", link: "https://www.geeksforgeeks.org/allocate-minimum-number-pages/" },
                    { question: "EKOSPOJ:", link: "https://www.geeksforgeeks.org/ekospoj-solution/" },
                    { question: "Job Scheduling Algo", link: "https://www.geeksforgeeks.org/job-sequencing-problem/" },
                    { question: "Missing Number in AP", link: "https://www.geeksforgeeks.org/find-missing-number-arithmetic-progression/" },
                    { question: "Smallest number with atleast n trailing zeroes in factorial", link: "https://www.geeksforgeeks.org/smallest-number-least-n-trailing-zeroes-factorial/" },
                    { question: "Painters Partition Problem:", link: "https://www.geeksforgeeks.org/painters-partition-problem/" },
                    { question: "ROTI-Prata SPOJ", link: "https://www.geeksforgeeks.org/rotprata-spoj-solution/" },
                    { question: "DoubleHelix SPOJ", link: "https://www.geeksforgeeks.org/doublehelix-spoj-solution/" },
                    { question: "Subset Sums", link: "https://www.geeksforgeeks.org/subset-sum-problem-dp-25/" },
                    { question: "Find the inversion count", link: "https://www.geeksforgeeks.org/counting-inversions/" },
                    { question: "Implement Merge-sort in-place", link: "https://www.geeksforgeeks.org/in-place-merge-sort/" },
                    { question: "Partitioning and Sorting Arrays with Many Repeated Entries", link: "https://www.geeksforgeeks.org/partitioning-sorting-arrays-many-repeated-entries/" },
                ],
                LinkedList: [
                    { question: "Write a Program to reverse the Linked List. (Both Iterative and recursive)", link: "https://www.geeksforgeeks.org/reverse-a-linked-list/" },
                    { question: "Reverse a Linked List in group of Given Size. [Very Imp]", link: "https://www.geeksforgeeks.org/reverse-a-list-in-groups-of-given-size/" },
                    { question: "Write a program to Detect loop in a linked list.", link: "https://www.geeksforgeeks.org/detect-loop-in-a-linked-list/" },
                    { question: "Write a program to Delete loop in a linked list.", link: "https://www.geeksforgeeks.org/detect-and-remove-loop-in-a-linked-list/" },
                    { question: "Find the starting point of the loop.", link: "https://www.geeksforgeeks.org/find-first-node-of-loop-in-a-linked-list/" },
                    { question: "Remove Duplicates in a sorted Linked List.", link: "https://www.geeksforgeeks.org/remove-duplicates-from-a-sorted-linked-list/" },
                    { question: "Remove Duplicates in a Un-sorted Linked List.", link: "https://www.geeksforgeeks.org/remove-duplicates-from-an-unsorted-linked-list/" },
                    { question: "Write a Program to Move the last element to Front in a Linked List.", link: "https://www.geeksforgeeks.org/move-last-element-to-front-of-a-given-linked-list/" },
                    { question: 'Add "1" to a number represented as a Linked List.', link: "https://www.geeksforgeeks.org/add-1-number-represented-linked-list/" },
                    { question: "Add two numbers represented by linked lists.", link: "https://www.geeksforgeeks.org/add-two-numbers-represented-by-linked-lists/" },
                    { question: "Intersection of two Sorted Linked List.", link: "https://www.geeksforgeeks.org/intersection-of-two-sorted-linked-lists/" },
                    { question: "Intersection Point of two Linked Lists.", link: "https://www.geeksforgeeks.org/write-a-function-to-get-the-intersection-point-of-two-linked-lists/" },
                    { question: "Merge Sort For Linked lists.[Very Important]", link: "https://www.geeksforgeeks.org/merge-sort-for-linked-list/" },
                    { question: "Quicksort for Linked Lists.[Very Important]", link: "https://www.geeksforgeeks.org/quicksort-on-singly-linked-list/" },
                    { question: "Find the middle Element of a linked list.", link: "https://www.geeksforgeeks.org/write-a-c-function-to-print-the-middle-of-the-linked-list/" },
                    { question: "Check if a linked list is a circular linked list.", link: "https://www.geeksforgeeks.org/check-if-a-linked-list-is-circular-linked-list/" },
                    { question: "Split a Circular linked list into two halves.", link: "https://www.geeksforgeeks.org/split-a-circular-linked-list-into-two-halves/" },
                    { question: "Write a Program to check whether the Singly Linked list is a palindrome or not.", link: "https://www.geeksforgeeks.org/function-to-check-if-a-singly-linked-list-is-palindrome/" },
                    { question: "Deletion from a Circular Linked List.", link: "https://www.geeksforgeeks.org/deletion-circular-linked-list/" },
                    { question: "Reverse a Doubly Linked list.", link: "https://www.geeksforgeeks.org/reverse-a-doubly-linked-list/" },
                    { question: "Find pairs with a given sum in a DLL.", link: "https://www.geeksforgeeks.org/find-pairs-given-sum-doubly-linked-list/" },
                    { question: 'Count triplets in a sorted DLL whose sum is equal to given value "X".', link: "https://www.geeksforgeeks.org/count-triplets-sorted-doubly-linked-list-whose-sum-equal-given-value-x/" },
                    { question: 'Sort a "k"sorted Doubly Linked list.[Very IMP]', link: "https://www.geeksforgeeks.org/sort-k-sorted-doubly-linked-list/" },
                    { question: "Rotate DoublyLinked list by N nodes.", link: "https://www.geeksforgeeks.org/rotate-doubly-linked-list-n-nodes/" },
                    { question: "Rotate a Doubly Linked list in group of Given Size.[Very IMP]", link: "https://www.geeksforgeeks.org/reverse-doubly-linked-list-groups-given-size/" },
                    { question: "Can we reverse a linked list in less than O(n) ?", link: "https://www.geeksforgeeks.org/can-we-reverse-a-linked-list-in-less-than-on/" },
                    { question: "Why Quicksort is preferred for. Arrays and Merge Sort for LinkedLists ?", link: "https://www.geeksforgeeks.org/why-quick-sort-preferred-for-arrays-and-merge-sort-for-linked-lists/" },
                    { question: "Flatten a Linked List", link: "https://www.geeksforgeeks.org/flattening-a-linked-list/" },
                    { question: "Sort a LL of 0s, 1s and 2s", link: "https://www.geeksforgeeks.org/sort-a-linked-list-of-0s-1s-or-2s/" },
                    { question: "Clone a linked list with next and random pointer", link: "https://www.geeksforgeeks.org/a-linked-list-with-next-and-arbit-pointer/" },
                    { question: "Merge K sorted Linked list", link: "https://www.geeksforgeeks.org/merge-k-sorted-linked-lists/" },
                    { question: "Multiply 2 no. represented by LL", link: "https://www.geeksforgeeks.org/multiply-two-numbers-represented-linked-lists/" },
                    { question: "Delete nodes which have a greater value on right side", link: "https://www.geeksforgeeks.org/delete-nodes-which-have-a-greater-value-on-right-side/" },
                    { question: "Segregate even and odd nodes in a Linked List", link: "https://www.geeksforgeeks.org/segregate-even-and-odd-elements-in-a-linked-list/" },
                    { question: "Program for nth node from the end of a Linked List", link: "https://www.geeksforgeeks.org/nth-node-from-the-end-of-a-linked-list/" },
                    { question: "Find the first non-repeating character from a stream of characters", link: "https://www.geeksforgeeks.org/find-first-non-repeating-character-stream-characters/" },
                ],
                "Binary Trees": [
                    { question: "level order traversal", link: "https://www.geeksforgeeks.org/level-order-tree-traversal/" },
                    { question: "Reverse Level Order traversal", link: "https://www.geeksforgeeks.org/reverse-level-order-traversal/" },
                    { question: "Height of a tree", link: "https://www.geeksforgeeks.org/write-a-c-program-to-find-the-maximum-depth-or-height-of-a-tree/" },
                    { question: "Diameter of a tree", link: "https://www.geeksforgeeks.org/diameter-of-a-binary-tree/" },
                    { question: "Mirror of a tree", link: "https://www.geeksforgeeks.org/create-a-mirror-tree-from-the-given-binary-tree/" },
                    { question: "Inorder Traversal of a tree both using recursion and Iteration", link: "https://www.geeksforgeeks.org/inorder-tree-traversal-without-recursion/" },
                    { question: "Preorder Traversal of a tree both using recursion and Iteration", link: "https://www.geeksforgeeks.org/iterative-preorder-traversal/" },
                    { question: "Postorder Traversal of a tree both using recursion and Iteration", link: "https://www.geeksforgeeks.org/iterative-postorder-traversal/" },
                    { question: "Left View of a tree", link: "https://www.geeksforgeeks.org/print-left-view-binary-tree/" },
                    { question: "Right View of Tree", link: "https://www.geeksforgeeks.org/print-right-view-binary-tree-2/" },
                    { question: "Top View of a tree", link: "https://www.geeksforgeeks.org/print-nodes-top-view-binary-tree/" },
                    { question: "Bottom View of a tree", link: "https://www.geeksforgeeks.org/bottom-view-binary-tree/" },
                    { question: "Zig-Zag traversal of a binary tree", link: "https://www.geeksforgeeks.org/zigzag-tree-traversal/" },
                    { question: "Check if a tree is balanced or not", link: "https://www.geeksforgeeks.org/how-to-determine-if-a-binary-tree-is-balanced/" },
                    { question: "Diagnol Traversal of a Binary tree", link: "https://www.geeksforgeeks.org/diagonal-traversal-of-binary-tree/" },
                    { question: "Boundary traversal of a Binary tree", link: "https://www.geeksforgeeks.org/boundary-traversal-of-binary-tree/" },
                    { question: "Construct Binary Tree from String with Bracket Representation", link: "https://www.geeksforgeeks.org/construct-binary-tree-string-bracket-representation/" },
                    { question: "Convert Binary tree into Doubly Linked List", link: "https://www.geeksforgeeks.org/convert-a-given-binary-tree-to-doubly-linked-list-set-2/" },
                    { question: "Convert Binary tree into Sum tree", link: "https://www.geeksforgeeks.org/convert-a-given-tree-to-sum-tree/" },
                    { question: "Construct Binary tree from Inorder and preorder traversal", link: "https://www.geeksforgeeks.org/construct-tree-from-given-inorder-and-preorder-traversal/" },
                    { question: "Find minimum swaps required to convert a Binary tree into BST", link: "https://www.geeksforgeeks.org/minimum-swap-required-convert-binary-tree-binary-search-tree/" },
                    { question: "Check if Binary tree is Sum tree or not", link: "https://www.geeksforgeeks.org/check-if-a-given-binary-tree-is-sumtree/" },
                    { question: "Check if all leaf nodes are at same level or not", link: "https://www.geeksforgeeks.org/check-leaves-level/" },
                    { question: "Check if a Binary Tree contains duplicate subtrees of size 2 or more [ IMP ]", link: "https://www.geeksforgeeks.org/check-binary-tree-contains-duplicate-subtrees-size-2/" },
                    { question: "Check if 2 trees are mirror or not", link: "https://www.geeksforgeeks.org/check-if-two-trees-are-mirror/" },
                    { question: "Sum of Nodes on the Longest path from root to leaf node", link: "https://www.geeksforgeeks.org/sum-nodes-longest-path-root-leaf-node/" },
                    { question: "Check if given graph is tree or not. [ IMP ]", link: "https://www.geeksforgeeks.org/check-given-graph-tree/" },
                    { question: "Find Largest subtree sum in a tree", link: "https://www.geeksforgeeks.org/find-largest-subtree-sum-tree/" },
                    { question: "Maximum Sum of nodes in Binary tree such that no two are adjacent", link: "https://www.geeksforgeeks.org/maximum-sum-nodes-binary-tree-no-two-adjacent/" },
                    { question: 'Print all "K" Sum paths in a Binary tree', link: "https://www.geeksforgeeks.org/print-k-sum-paths-binary-tree/" },
                    { question: "Find LCA in a Binary tree", link: "https://www.geeksforgeeks.org/lowest-common-ancestor-binary-tree-set-1/" },
                    { question: "Find distance between 2 nodes in a Binary tree", link: "https://www.geeksforgeeks.org/find-distance-between-two-nodes-of-a-binary-tree/" },
                    { question: "Kth Ancestor of node in a Binary tree", link: "https://www.geeksforgeeks.org/kth-ancestor-node-binary-tree/" },
                    { question: "Find all Duplicate subtrees in a Binary tree [ IMP ]", link: "https://www.geeksforgeeks.org/find-duplicate-subtrees/" },
                    { question: "Tree Isomorphism Problem", link: "https://www.geeksforgeeks.org/tree-isomorphism-problem/" },
                ],
                "Binary Search Trees": [
                    { question: "Find a value in a BST", link: "https://www.geeksforgeeks.org/binary-search-tree-set-1-search-and-insertion/" },
                    { question: "Deletion of a node in a BST", link: "https://www.geeksforgeeks.org/binary-search-tree-set-2-delete/" },
                    { question: "Find min and max value in a BST", link: "https://www.geeksforgeeks.org/find-the-minimum-and-maximum-value-node-in-binary-search-tree/" },
                    { question: "Find inorder successor and inorder predecessor in a BST", link: "https://www.geeksforgeeks.org/inorder-predecessor-successor-given-key-bst/" },
                    { question: "Check if a tree is a BST or not", link: "https://www.geeksforgeeks.org/a-program-to-check-if-a-binary-tree-is-bst-or-not/" },
                    { question: "Populate Inorder successor of all nodes", link: "https://www.geeksforgeeks.org/populate-inorder-successor-for-all-nodes/" },
                    { question: "Find LCA of 2 nodes in a BST", link: "https://www.geeksforgeeks.org/lowest-common-ancestor-in-a-binary-search-tree/" },
                    { question: "Construct BST from preorder traversal", link: "https://www.geeksforgeeks.org/construct-bst-from-given-preorder-traversa/" },
                    { question: "Convert Binary tree into BST", link: "https://www.geeksforgeeks.org/binary-tree-to-binary-search-tree-conversion/" },
                    { question: "Convert a normal BST into a Balanced BST", link: "https://www.geeksforgeeks.org/convert-normal-bst-balanced-bst/" },
                    { question: "Merge two BST [ V.V.V>IMP ]", link: "https://www.geeksforgeeks.org/merge-two-balanced-binary-search-trees/" },
                    { question: "Find Kth largest element in a BST", link: "https://www.geeksforgeeks.org/kth-largest-element-in-bst-when-modification-to-bst-is-not-allowed/" },
                    { question: "Find Kth smallest element in a BST", link: "https://www.geeksforgeeks.org/find-k-th-smallest-element-in-bst-order-statistics-in-bst/" },
                    { question: 'Count pairs from 2 BST whose sum is equal to given value "X"', link: "https://www.geeksforgeeks.org/count-pairs-from-two-bsts-whose-sum-is-equal-to-a-given-value-x/" },
                    { question: "Find the median of BST in O(n) time and O(1) space", link: "https://www.geeksforgeeks.org/find-median-bst-time-o1-space/" },
                    { question: "Count BST nodes that lie in a given range", link: "https://www.geeksforgeeks.org/count-bst-nodes-that-are-in-a-given-range/" },
                    { question: "Replace every element with the least greater element on its right", link: "https://www.geeksforgeeks.org/replace-every-element-with-the-least-greater-element-on-its-right/" },
                    { question: 'Given "n" appointments, find the conflicting appointments', link: "https://www.geeksforgeeks.org/given-n-appointments-find-conflicting-appointments/" },
                    { question: "Check preorder is valid or not", link: "https://www.geeksforgeeks.org/check-if-a-given-array-can-represent-preorder-traversal-of-binary-search-tree/" },
                    { question: "Check whether BST contains Dead end", link: "https://www.geeksforgeeks.org/check-whether-bst-contains-dead-end-not/" },
                    { question: "Largest BST in a Binary Tree [ V.V.V.V.V IMP ]", link: "https://www.geeksforgeeks.org/largest-bst-binary-tree-set-2/" },
                    { question: "Flatten BST to sorted list", link: "https://www.geeksforgeeks.org/flatten-bst-to-sorted-list-increasing-order/" },
                ],
                Greedy: [
                    { question: "Activity Selection Problem", link: "https://www.geeksforgeeks.org/activity-selection-problem-greedy-algo-1/" },
                    { question: "Job Sequencing Problem", link: "https://www.geeksforgeeks.org/job-sequencing-problem/" },
                    { question: "Huffman Coding", link: "https://www.geeksforgeeks.org/huffman-coding-greedy-algo-3/" },
                    { question: "Water Connection Problem", link: "https://www.geeksforgeeks.org/water-connection-problem/" },
                    { question: "Fractional Knapsack Problem", link: "https://www.geeksforgeeks.org/fractional-knapsack-problem/" },
                    { question: "Greedy Algorithm to find Minimum number of Coins", link: "https://www.geeksforgeeks.org/greedy-algorithm-to-find-minimum-number-of-coins/" },
                    { question: "Maximum trains for which stoppage can be provided", link: "https://www.geeksforgeeks.org/maximum-trains-stoppage-can-provided/" },
                    { question: "Minimum Platforms Problem", link: "https://www.geeksforgeeks.org/minimum-number-platforms-required-railwaybus-station/" },
                    { question: "Buy Maximum Stocks if i stocks can be bought on i-th day", link: "https://www.geeksforgeeks.org/buy-maximum-stocks-stocks-can-bought-th-day/" },
                    { question: "Find the minimum and maximum amount to buy all N candies", link: "https://www.geeksforgeeks.org/find-minimum-maximum-amount-buy-n-candies/" },
                    { question: "Minimize Cash Flow among a given set of friends who have borrowed money from each other", link: "https://www.geeksforgeeks.org/minimize-cash-flow-among-given-set-friends-borrowed-money/" },
                    { question: "Minimum Cost to cut a board into squares", link: "https://www.geeksforgeeks.org/minimum-cost-cut-board-squares/" },
                    { question: "Check if it is possible to survive on Island", link: "https://www.geeksforgeeks.org/survival/" },
                    { question: "Find maximum meetings in one room", link: "https://www.geeksforgeeks.org/find-maximum-meetings-in-one-room/" },
                    { question: "Maximum product subset of an array", link: "https://www.geeksforgeeks.org/maximum-product-subset-array/" },
                    { question: "Maximize array sum after K negations", link: "https://www.geeksforgeeks.org/maximize-array-sun-after-k-negation-operations/" },
                    { question: "Maximize the sum of arr[i]*i", link: "https://www.geeksforgeeks.org/maximize-sum-arrii/" },
                    { question: "Maximum sum of absolute difference of an array", link: "https://www.geeksforgeeks.org/maximum-sum-absolute-difference-array/" },
                    { question: "Maximize sum of consecutive differences in a circular array", link: "https://www.geeksforgeeks.org/maximize-sum-consecutive-differences-circular-array/" },
                    { question: "Minimum sum of absolute difference of pairs of two arrays", link: "https://www.geeksforgeeks.org/minimum-sum-absolute-difference-pairs-two-arrays/" },
                    { question: "Program for Shortest Job First (or SJF) CPU Scheduling", link: "https://www.geeksforgeeks.org/program-for-shortest-job-first-or-sjf-cpu-scheduling-set-1-non-preemptive/" },
                    { question: "Program for Least Recently Used (LRU) Page Replacement algorithm", link: "https://www.geeksforgeeks.org/program-for-least-recently-used-lru-page-replacement-algorithm/" },
                    { question: "Smallest subset with sum greater than all other elements", link: "https://www.geeksforgeeks.org/smallest-subset-sum-greater-elements/" },
                    { question: "Chocolate Distribution Problem", link: "https://www.geeksforgeeks.org/chocolate-distribution-problem/" },
                    { question: "DEFKIN -Defense of a Kingdom", link: "https://www.geeksforgeeks.org/defkin-defense-of-a-kingdom/" },
                    { question: "DIEHARD -DIE HARD", link: "https://www.geeksforgeeks.org/die-hard-problem/" },
                    { question: "GERGOVIA -Wine trading in Gergovia", link: "https://www.geeksforgeeks.org/gergovia-wine-trading/" },
                    { question: "Picking Up Chicks", link: "https://www.geeksforgeeks.org/picking-up-chicks/" },
                    { question: "CHOCOLA –Chocolate", link: "https://www.geeksforgeeks.org/chocolate-distribution-problem/" },
                    { question: "ARRANGE -Arranging Amplifiers", link: "https://www.geeksforgeeks.org/arrange-amplifiers/" },
                    { question: "K Centers Problem", link: "https://www.geeksforgeeks.org/k-centers-problem-set-1-greedy-approximate-algorithm/" },
                    { question: "Minimum Cost of ropes", link: "https://www.geeksforgeeks.org/connect-n-ropes-minimum-cost/" },
                    { question: "Find smallest number with given number of digits and sum of digits", link: "https://www.geeksforgeeks.org/find-smallest-number-with-given-number-of-digits-and-digit-sum/" },
                    { question: "Rearrange characters in a string such that no two adjacent are same", link: "https://www.geeksforgeeks.org/rearrange-characters-string-no-two-adjacent/" },
                    { question: "Find maximum sum possible equal sum of three stacks", link: "https://www.geeksforgeeks.org/find-maximum-sum-possible-equal-sum-three-stacks/" },
                ],
                BackTracking: [
                    { question: "Rat in a maze Problem", link: "https://www.geeksforgeeks.org/rat-in-a-maze-backtracking-2/" },
                    { question: "Printing all solutions in N-Queen Problem", link: "https://www.geeksforgeeks.org/printing-solutions-n-queen-problem/" },
                    { question: "Word Break Problem using Backtracking", link: "https://www.geeksforgeeks.org/word-break-problem-using-backtracking/" },
                    { question: "Remove Invalid Parentheses", link: "https://www.geeksforgeeks.org/remove-invalid-parentheses/" },
                    { question: "Sudoku Solver", link: "https://www.geeksforgeeks.org/sudoku-backtracking-7/" },
                    { question: "m Coloring Problem", link: "https://www.geeksforgeeks.org/m-coloring-problem-backtracking-5/" },
                    { question: "Print all palindromic partitions of a string", link: "https://www.geeksforgeeks.org/given-a-string-print-all-possible-palindromic-partition/" },
                    { question: "Subset Sum Problem", link: "https://www.geeksforgeeks.org/subset-sum-backtracking-4/" },
                    { question: "The Knights tour problem", link: "https://www.geeksforgeeks.org/the-knights-tour-problem-backtracking-1/" },
                    { question: "Tug of War", link: "https://www.geeksforgeeks.org/tug-of-war/" },
                    { question: "Find shortest safe route in a path with landmines", link: "https://www.geeksforgeeks.org/find-shortest-safe-route-in-a-path-with-landmines/" },
                    { question: "Combinational Sum", link: "https://www.geeksforgeeks.org/combinational-sum/" },
                    { question: "Find Maximum number possible by doing at-most K swaps", link: "https://www.geeksforgeeks.org/find-maximum-number-possible-by-doing-at-most-k-swaps/" },
                    { question: "Print all permutations of a string", link: "https://www.geeksforgeeks.org/write-a-c-program-to-print-all-permutations-of-a-given-string/" },
                    { question: "Find if there is a path of more than k length from a source", link: "https://www.geeksforgeeks.org/find-if-there-is-a-path-of-more-than-k-length-from-a-source/" },
                    { question: "Longest Possible Route in a Matrix with Hurdles", link: "https://www.geeksforgeeks.org/longest-possible-route-in-a-matrix-with-hurdles/" },
                    { question: "Print all possible paths from top left to bottom right of a mXn matrix", link: "https://www.geeksforgeeks.org/print-all-possible-paths-from-top-left-to-bottom-right-of-a-mxn-matrix/" },
                    { question: "Partition of a set into K subsets with equal sum", link: "https://www.geeksforgeeks.org/partition-set-k-subsets-equal-sum/" },
                    { question: "Find the K-th Permutation Sequence of first N natural numbers", link: "https://www.geeksforgeeks.org/find-the-k-th-permutation-sequence-of-first-n-natural-numbers/" },
                ],
                "Stacks & Queues": [
                    { question: "Implement Stack from Scratch", link: "https://www.geeksforgeeks.org/stack-data-structure-introduction-program/" },
                    { question: "Implement Queue from Scratch", link: "https://www.geeksforgeeks.org/queue-data-structure/" },
                    { question: "Implement 2 stack in an array", link: "https://www.geeksforgeeks.org/implement-two-stacks-in-an-array/" },
                    { question: "find the middle element of a stack", link: "https://www.geeksforgeeks.org/design-a-stack-with-find-middle-operation/" },
                    { question: 'Implement "N" stacks in an Array', link: "https://www.geeksforgeeks.org/efficiently-implement-k-stacks-single-array/" },
                    { question: "Check the expression has valid or Balanced parenthesis or not.", link: "https://www.geeksforgeeks.org/check-for-balanced-parentheses-in-an-expression/" },
                    { question: "Reverse a String using Stack", link: "https://www.geeksforgeeks.org/stack-set-3-reverse-string-using-stack/" },
                    { question: "Design a Stack that supports getMin() in O(1) time and O(1) extra space.", link: "https://www.geeksforgeeks.org/design-a-stack-that-supports-getmin-in-o1-time-and-o1-extra-space/" },
                    { question: "Find the next Greater element", link: "https://www.geeksforgeeks.org/next-greater-element/" },
                    { question: "The celebrity Problem", link: "https://www.geeksforgeeks.org/the-celebrity-problem/" },
                    { question: "Arithmetic Expression evaluation", link: "https://www.geeksforgeeks.org/arithmetic-expression-evalution/" },
                    { question: "Evaluation of Postfix expression", link: "https://www.geeksforgeeks.org/stack-set-4-evaluation-postfix-expression/" },
                    { question: "Implement a method to insert an element at its bottom without using any other data structure.", link: "https://www.geeksforgeeks.org/insert-element-at-the-bottom-of-a-stack/" },
                    { question: "Reverse a stack using recursion", link: "https://www.geeksforgeeks.org/reverse-a-stack-using-recursion/" },
                    { question: "Sort a Stack using recursion", link: "https://www.geeksforgeeks.org/sort-a-stack-using-recursion/" },
                    { question: "Merge Overlapping Intervals", link: "https://www.geeksforgeeks.org/merging-intervals/" },
                    { question: "Largest rectangular Area in Histogram", link: "https://www.geeksforgeeks.org/largest-rectangle-under-histogram/" },
                    { question: "Length of the Longest Valid Substring", link: "https://www.geeksforgeeks.org/length-of-the-longest-valid-substring/" },
                    { question: "Expression contains redundant bracket or not", link: "https://www.geeksforgeeks.org/expression-contains-redundant-bracket-not/" },
                    { question: "Implement Stack using Queue", link: "https://www.geeksforgeeks.org/implement-stack-using-queue/" },
                    { question: "Implement Stack using Deque", link: "https://www.geeksforgeeks.org/implement-stack-using-deque/" },
                    { question: "Stack Permutations (Check if an array is stack permutation of other)", link: "https://www.geeksforgeeks.org/stack-permutations-check-if-an-array-is-stack-permutation-of-other/" },
                    { question: "Implement Queue using Stack", link: "https://www.geeksforgeeks.org/queue-using-stacks/" },
                    { question: 'Implement "n" queue in an array', link: "https://www.geeksforgeeks.org/efficiently-implement-k-queues-single-array/" },
                    { question: "Implement a Circular queue", link: "https://www.geeksforgeeks.org/circular-queue-set-1-introduction-array-implementation/" },
                    { question: "LRU Cache Implementation", link: "https://www.geeksforgeeks.org/lru-cache-implementation/" },
                    { question: "Reverse a Queue using recursion", link: "https://www.geeksforgeeks.org/reversing-a-queue-using-recursion/" },
                    { question: 'Reverse the first "K" elements of a queue', link: "https://www.geeksforgeeks.org/reversing-first-k-elements-queue/" },
                    { question: "Interleave the first half of the queue with second half", link: "https://www.geeksforgeeks.org/interleave-first-half-queue-second-half/" },
                    { question: "Find the first circular tour that visits all Petrol Pumps", link: "https://www.geeksforgeeks.org/find-a-tour-that-visits-all-stations/" },
                    { question: "Minimum time required to rot all oranges", link: "https://www.geeksforgeeks.org/minimum-time-required-so-that-all-oranges-become-rotten/" },
                    { question: "Distance of nearest cell having 1 in a binary matrix", link: "https://www.geeksforgeeks.org/distance-nearest-cell-1-binary-matrix/" },
                    { question: 'First negative integer in every window of size "k"', link: "https://www.geeksforgeeks.org/first-negative-integer-every-window-size-k/" },
                    { question: "Check if all levels of two trees are anagrams or not.", link: "https://www.geeksforgeeks.org/check-if-all-levels-of-two-trees-are-anagrams-or-not/" },
                    { question: 'Sum of minimum and maximum elements of all subarrays of size "k".', link: "https://www.geeksforgeeks.org/sum-minimum-maximum-elements-subarrays-size-k/" },
                    {
                        question: 'Minimum sum of squares of character counts in a given string after removing "k" characters.',
                        link: "https://www.geeksforgeeks.org/minimum-sum-squares-characters-counts-given-string-removing-k-characters/",
                    },
                    { question: "Queue based approach or first non-repeating character in a stream.", link: "https://www.geeksforgeeks.org/queue-based-approach-for-first-non-repeating-character-in-a-stream/" },
                    { question: "Next Smaller Element", link: "https://www.geeksforgeeks.org/next-smaller-element/" },
                ],
                Heap: [
                    { question: "Implement a Maxheap/MinHeap using arrays and recursion.", link: "https://www.geeksforgeeks.org/building-heap-from-array/" },
                    { question: "Sort an Array using heap. (HeapSort)", link: "https://www.geeksforgeeks.org/heap-sort/" },
                    { question: "Maximum of all subarrays of size k.", link: "https://www.geeksforgeeks.org/sliding-window-maximum-maximum-of-all-subarrays-of-size-k/" },
                    { question: '"k" largest element in an array', link: "https://www.geeksforgeeks.org/k-largestor-smallest-elements-in-an-array/" },
                    { question: "Kth smallest and largest element in an unsorted array", link: "https://www.geeksforgeeks.org/kth-smallestlargest-element-unsorted-array/" },
                    { question: 'Merge "K" sorted arrays. [ IMP ]', link: "https://www.geeksforgeeks.org/merge-k-sorted-arrays/" },
                    { question: "Merge 2 Binary Max Heaps", link: "https://www.geeksforgeeks.org/merge-two-binary-max-heaps/" },
                    { question: "Kth largest sum continuous subarrays", link: "https://www.geeksforgeeks.org/k-th-largest-sum-contiguous-subarray/" },
                    { question: "Leetcode- reorganize strings", link: "https://www.geeksforgeeks.org/rearrange-characters-string-no-two-adjacent/" },
                    { question: 'Merge "K" Sorted Linked Lists [V.IMP]', link: "https://www.geeksforgeeks.org/merge-k-sorted-linked-lists/" },
                    { question: 'Smallest range in "K" Lists', link: "https://www.geeksforgeeks.org/find-smallest-range-containing-elements-from-k-lists/" },
                    { question: "Median in a stream of Integers", link: "https://www.geeksforgeeks.org/median-of-stream-of-integers-running-integers/" },
                    { question: "Check if a Binary Tree is Heap", link: "https://www.geeksforgeeks.org/check-if-a-given-binary-tree-is-heap/" },
                    { question: 'Connect "n" ropes with minimum cost', link: "https://www.geeksforgeeks.org/connect-n-ropes-minimum-cost/" },
                    { question: "Convert BST to Min Heap", link: "https://www.geeksforgeeks.org/convert-bst-min-heap/" },
                    { question: "Convert min heap to max heap", link: "https://www.geeksforgeeks.org/convert-min-heap-to-max-heap/" },
                    { question: "Rearrange characters in a string such that no two adjacent are same.", link: "https://www.geeksforgeeks.org/rearrange-characters-string-no-two-adjacent/" },
                    { question: "Minimum sum of two numbers formed from digits of an array", link: "https://www.geeksforgeeks.org/minimum-sum-two-numbers-formed-digits-array/" },
                ],
                Graph: [
                    { question: "Create a Graph, print it", link: "https://www.geeksforgeeks.org/graph-and-its-representations/" },
                    { question: "Implement BFS algorithm", link: "https://www.geeksforgeeks.org/breadth-first-search-or-bfs-for-a-graph/" },
                    { question: "Implement DFS Algo", link: "https://www.geeksforgeeks.org/depth-first-search-or-dfs-for-a-graph/" },
                    { question: "Detect Cycle in Directed Graph using BFS/DFS Algo", link: "https://www.geeksforgeeks.org/detect-cycle-in-a-graph/" },
                    { question: "Detect Cycle in UnDirected Graph using BFS/DFS Algo", link: "https://www.geeksforgeeks.org/detect-cycle-undirected-graph/" },
                    { question: "Search in a Maze", link: "https://www.geeksforgeeks.org/rat-in-a-maze-backtracking-2/" },
                    { question: "Minimum Step by Knight", link: "https://www.geeksforgeeks.org/minimum-steps-reach-target-knight/" },
                    { question: "flood fill algo", link: "https://www.geeksforgeeks.org/flood-fill-algorithm-implement-fill-paint/" },
                    { question: "Clone a graph", link: "https://www.geeksforgeeks.org/clone-an-undirected-graph/" },
                    { question: "Making wired Connections", link: "https://www.geeksforgeeks.org/connect-nodes-at-same-level/" },
                    { question: "word Ladder", link: "https://www.geeksforgeeks.org/word-ladder-length-of-shortest-chain-to-reach-a-target-word/" },
                    { question: "Dijkstra algo", link: "https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/" },
                    { question: "Implement Topological Sort", link: "https://www.geeksforgeeks.org/topological-sorting/" },
                    { question: "Minimum time taken by each job to be completed given by a Directed Acyclic Graph", link: "https://www.geeksforgeeks.org/minimum-time-taken-by-each-job-to-be-completed-given-by-a-directed-acyclic-graph/" },
                    { question: "Find whether it is possible to finish all tasks or not from given dependencies", link: "https://www.geeksforgeeks.org/find-whether-it-is-possible-to-finish-all-tasks-or-not-from-given-dependencies/" },
                    { question: "Find the no. of Islands", link: "https://www.geeksforgeeks.org/find-number-of-islands/" },
                    { question: "Given a sorted Dictionary of an Alien Language, find order of characters", link: "https://www.geeksforgeeks.org/given-sorted-dictionary-find-precedence-characters/" },
                    { question: "Implement KruksalsAlgorithm", link: "https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/" },
                    { question: "Implement Prims Algorithm", link: "https://www.geeksforgeeks.org/prims-minimum-spanning-tree-mst-greedy-algo-5/" },
                    { question: "Total no. of Spanning tree in a graph", link: "https://www.geeksforgeeks.org/total-number-spanning-trees-graph/" },
                    { question: "Implement Bellman Ford Algorithm", link: "https://www.geeksforgeeks.org/bellman-ford-algorithm-dp-23/" },
                    { question: "Implement Floyd warshallAlgorithm", link: "https://www.geeksforgeeks.org/floyd-warshall-algorithm-dp-16/" },
                    { question: "Travelling Salesman Problem", link: "https://www.geeksforgeeks.org/travelling-salesman-problem-set-1/" },
                    { question: "Graph ColouringProblem", link: "https://www.geeksforgeeks.org/graph-coloring-applications/" },
                    { question: "Snake and Ladders Problem", link: "https://www.geeksforgeeks.org/snake-ladder-problem-2/" },
                    { question: "Find bridge in a graph", link: "https://www.geeksforgeeks.org/bridge-in-a-graph/" },
                    { question: "Count Strongly connected Components(Kosaraju Algo)", link: "https://www.geeksforgeeks.org/strongly-connected-components/" },
                    { question: "Check whether a graph is Bipartite or Not", link: "https://www.geeksforgeeks.org/bipartite-graph/" },
                    { question: "Detect Negative cycle in a graph", link: "https://www.geeksforgeeks.org/detect-negative-cycle-graph-bellman-ford/" },
                    { question: "Longest path in a Directed Acyclic Graph", link: "https://www.geeksforgeeks.org/find-longest-path-directed-acyclic-graph/" },
                    { question: "Journey to the Moon", link: "https://www.geeksforgeeks.org/journey-to-the-moon/" },
                    { question: "Cheapest Flights Within K Stops", link: "https://www.geeksforgeeks.org/cheapest-flights-within-k-stops/" },
                    { question: "Oliver and the Game", link: "https://www.geeksforgeeks.org/oliver-and-the-game/" },
                    { question: "Water Jug problem using BFS", link: "https://www.geeksforgeeks.org/water-jug-problem-using-bfs/" },
                    { question: "Find if there is a path of more thank length from a source", link: "https://www.geeksforgeeks.org/find-if-there-is-a-path-of-more-than-k-length-from-a-source/" },
                    { question: "M-ColouringProblem", link: "https://www.geeksforgeeks.org/m-coloring-problem-backtracking-5/" },
                    { question: "Minimum edges to reverse o make path from source to destination", link: "https://www.geeksforgeeks.org/minimum-edges-reverse-make-path-source-destination/" },
                    { question: "Paths to travel each nodes using each edge(Seven Bridges)", link: "https://www.geeksforgeeks.org/eulerian-path-and-circuit/" },
                    { question: "Vertex Cover Problem", link: "https://www.geeksforgeeks.org/vertex-cover-problem-set-1-introduction-approximate-algorithm-2/" },
                    { question: "Chinese Postman or Route Inspection", link: "https://www.geeksforgeeks.org/chinese-postman-route-inspection-set-1-introduction/" },
                    { question: "Number of Triangles in a Directed and Undirected Graph", link: "https://www.geeksforgeeks.org/number-of-triangles-in-directed-and-undirected-graphs/" },
                    { question: "Minimise the cashflow among a given set of friends who have borrowed money from each other", link: "https://www.geeksforgeeks.org/minimize-cash-flow-among-given-set-friends-borrowed-money/" },
                    { question: "Two Clique Problem", link: "https://www.geeksforgeeks.org/two-clique-problem-check-graph-can-divided-two-cliques/" },
                ],
                Trie: [
                    { question: "Construct a trie from scratch", link: "https://www.geeksforgeeks.org/trie-insert-and-search/" },
                    { question: "Find shortest unique prefix for every word in a given list", link: "https://www.geeksforgeeks.org/find-all-shortest-unique-prefixes-to-represent-each-word-in-a-given-list/" },
                    { question: "Word Break Problem | (Trie solution)", link: "https://www.geeksforgeeks.org/word-break-problem-trie-solution/" },
                    { question: "Given a sequence of words, print all anagrams together", link: "https://www.geeksforgeeks.org/given-a-sequence-of-words-print-all-anagrams-together/" },
                    { question: "Implement a Phone Directory", link: "https://www.geeksforgeeks.org/implement-a-phone-directory/" },
                    { question: "Print unique rows in a given boolean matrix", link: "https://www.geeksforgeeks.org/print-unique-rows/" },
                ],
                "Dynamic Programming": [
                    { question: "Coin ChangeProblem", link: "https://www.geeksforgeeks.org/coin-change-dp-7/" },
                    { question: "Knapsack Problem", link: "https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/" },
                    { question: "Binomial CoefficientProblem", link: "https://www.geeksforgeeks.org/binomial-coefficient-dp-9/" },
                    { question: "Permutation CoefficientProblem", link: "https://www.geeksforgeeks.org/permutation-coefficient/" },
                    { question: "Program for nth Catalan Number", link: "https://www.geeksforgeeks.org/program-nth-catalan-number/" },
                    { question: "Matrix Chain Multiplication", link: "https://www.geeksforgeeks.org/matrix-chain-multiplication-dp-8/" },
                    { question: "Edit Distance", link: "https://www.geeksforgeeks.org/edit-distance-dp-5/" },
                    { question: "Subset Sum Problem", link: "https://www.geeksforgeeks.org/subset-sum-problem-dp-25/" },
                    { question: "Friends Pairing Problem", link: "https://www.geeksforgeeks.org/friends-pairing-problem/" },
                    { question: "Gold Mine Problem", link: "https://www.geeksforgeeks.org/gold-mine-problem/" },
                    { question: "Assembly Line SchedulingProblem", link: "https://www.geeksforgeeks.org/assembly-line-scheduling-dp-34/" },
                    { question: "Painting the Fenceproblem", link: "https://www.geeksforgeeks.org/painting-fence-algorithm/" },
                    { question: "Maximize The Cut Segments", link: "https://www.geeksforgeeks.org/maximize-the-number-of-segments-of-length-p-q-and-r/" },
                    { question: "Longest Common Subsequence", link: "https://www.geeksforgeeks.org/longest-common-subsequence-dp-4/" },
                    { question: "Longest Repeated Subsequence", link: "https://www.geeksforgeeks.org/longest-repeated-subsequence/" },
                    { question: "Longest Increasing Subsequence", link: "https://www.geeksforgeeks.org/longest-increasing-subsequence-dp-3/" },
                    { question: "Space Optimized Solution of LCS", link: "https://www.geeksforgeeks.org/space-optimized-solution-lcs/" },
                    { question: "LCS (Longest Common Subsequence) of three strings", link: "https://www.geeksforgeeks.org/lcs-longest-common-subsequence-three-strings/" },
                    { question: "Maximum Sum Increasing Subsequence", link: "https://www.geeksforgeeks.org/maximum-sum-increasing-subsequence-dp-14/" },
                    { question: "Count all subsequences having product less than K", link: "https://www.geeksforgeeks.org/count-subsequences-product-less-k/" },
                    { question: "Longest subsequence such that difference between adjacent is one", link: "https://www.geeksforgeeks.org/longest-subsequence-such-that-difference-between-adjacents-is-one/" },
                    { question: "Maximum subsequence sum such that no three are consecutive", link: "https://www.geeksforgeeks.org/maximum-subsequence-sum-such-that-no-three-are-consecutive/" },
                    { question: "Egg Dropping Problem", link: "https://www.geeksforgeeks.org/egg-dropping-puzzle-dp-11/" },
                    { question: "Maximum Length Chain of Pairs", link: "https://www.geeksforgeeks.org/maximum-length-chain-of-pairs-dp-20/" },
                    { question: "Maximum size square sub-matrix with all 1s", link: "https://www.geeksforgeeks.org/maximum-size-sub-matrix-with-all-1s-in-a-binary-matrix/" },
                    { question: "Maximum sum of pairs with specific difference", link: "https://www.geeksforgeeks.org/maximum-sum-pairs-specific-difference/" },
                    { question: "Min Cost PathProblem", link: "https://www.geeksforgeeks.org/min-cost-path-dp-6/" },
                    { question: "Maximum difference of zeros and ones in binary string", link: "https://www.geeksforgeeks.org/maximum-difference-zeros-ones-binary-string/" },
                    { question: "Minimum number of jumps to reach end", link: "https://www.geeksforgeeks.org/minimum-number-of-jumps-to-reach-end-of-a-given-array/" },
                    { question: "Minimum cost to fill given weight in a bag", link: "https://www.geeksforgeeks.org/minimum-cost-to-fill-given-weight-in-a-bag/" },
                    { question: "Minimum removals from array to make max –min <= K", link: "https://www.geeksforgeeks.org/minimum-removals-array-make-max-min-k/" },
                    { question: "Longest Common Substring", link: "https://www.geeksforgeeks.org/longest-common-substring-dp-29/" },
                    { question: "Count number of ways to reach a given score in a game", link: "https://www.geeksforgeeks.org/count-number-ways-reach-given-score-game/" },
                    { question: "Count Balanced Binary Trees of Height h", link: "https://www.geeksforgeeks.org/count-balanced-binary-trees-height-h/" },
                    { question: "LargestSum Contiguous Subarray [V>V>V>V IMP ]", link: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/" },
                    { question: "Smallest sum contiguous subarray", link: "https://www.geeksforgeeks.org/smallest-sum-contiguous-subarray/" },
                    { question: "Unbounded Knapsack (Repetition of items allowed)", link: "https://www.geeksforgeeks.org/unbounded-knapsack-repetition-items-allowed/" },
                    { question: "Word Break Problem", link: "https://www.geeksforgeeks.org/word-break-problem-dp-32/" },
                    { question: "Largest Independent Set Problem", link: "https://www.geeksforgeeks.org/largest-independent-set-problem-dp-26/" },
                    { question: "Partition problem", link: "https://www.geeksforgeeks.org/partition-problem-dp-18/" },
                    { question: "Longest Palindromic Subsequence", link: "https://www.geeksforgeeks.org/longest-palindromic-subsequence-dp-12/" },
                    { question: "Count All Palindromic Subsequence in a given String", link: "https://www.geeksforgeeks.org/count-palindromic-subsequence-given-string/" },
                    { question: "Longest Palindromic Substring", link: "https://www.geeksforgeeks.org/longest-palindrome-substring-set-1/" },
                    { question: "Longest alternating subsequence", link: "https://www.geeksforgeeks.org/longest-alternating-subsequence/" },
                    { question: "Weighted Job Scheduling", link: "https://www.geeksforgeeks.org/weighted-job-scheduling/" },
                    { question: "Coin game winner where every player has three choices", link: "https://www.geeksforgeeks.org/coin-game-winner-every-player-three-choices/" },
                    {
                        question: "Count Derangements (Permutation such that no element appears in its original position) [ IMPORTANT ]",
                        link: "https://www.geeksforgeeks.org/count-derangements-permutation-such-that-no-element-appears-in-its-original-position/",
                    },
                    { question: "Maximum profit by buying and selling a share at most twice [ IMP ]", link: "https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-twice/" },
                    { question: "Optimal Strategy for a Game", link: "https://www.geeksforgeeks.org/optimal-strategy-for-a-game-dp-31/" },
                    { question: "Optimal Binary Search Tree", link: "https://www.geeksforgeeks.org/optimal-binary-search-tree-dp-24/" },
                    { question: "Palindrome PartitioningProblem", link: "https://www.geeksforgeeks.org/palindrome-partitioning-dp-17/" },
                    { question: "Word Wrap Problem", link: "https://www.geeksforgeeks.org/word-wrap-problem-dp-19/" },
                    { question: "Mobile Numeric Keypad Problem [ IMP ]", link: "https://www.geeksforgeeks.org/mobile-numeric-keypad-problem/" },
                    { question: "Boolean Parenthesization Problem", link: "https://www.geeksforgeeks.org/boolean-parenthesization-problem-dp-37/" },
                    { question: "Largest rectangular sub-matrix whose sum is 0", link: "https://www.geeksforgeeks.org/largest-rectangular-sub-matrix-whose-sum-0/" },
                    { question: "Largest area rectangular sub-matrix with equal number of 1s and 0s [ IMP ]", link: "https://www.geeksforgeeks.org/largest-area-rectangular-sub-matrix-equal-number-1s-0s/" },
                    { question: "Maximum sum rectangle in a 2D matrix", link: "https://www.geeksforgeeks.org/maximum-sum-rectangle-in-a-2d-matrix-dp-27/" },
                    { question: "Maximum profit by buying and selling a share at most k times", link: "https://www.geeksforgeeks.org/maximum-profit-by-buying-and-selling-a-share-at-most-k-times/" },
                    { question: "Find if a string is interleaved of two other strings", link: "https://www.geeksforgeeks.org/check-whether-a-given-string-is-an-interleaving-of-two-other-given-strings/" },
                    { question: "Maximum Length of Pair Chain", link: "https://www.geeksforgeeks.org/maximum-length-chain-of-pairs-dp-20/" },
                ],
                "Bit Manipulation": [
                    { question: "Count set bits in an integer", link: "https://www.geeksforgeeks.org/count-set-bits-in-an-integer/" },
                    { question: "Find the two non-repeating elements in an array of repeating elements", link: "https://www.geeksforgeeks.org/find-two-non-repeating-elements-in-an-array-of-repeating-elements/" },
                    { question: "Count number of bits to be flipped to convert A to B", link: "https://www.geeksforgeeks.org/count-number-of-bits-to-be-flipped-to-convert-a-to-b/" },
                    { question: "Count total set bits in all numbers from 1 to n", link: "https://www.geeksforgeeks.org/count-total-set-bits-in-all-numbers-from-1-to-n/" },
                    { question: "Program to find whether a no is power of two", link: "https://www.geeksforgeeks.org/program-to-find-whether-a-no-is-power-of-two/" },
                    { question: "Find position of the only set bit", link: "https://www.geeksforgeeks.org/find-position-of-the-only-set-bit/" },
                    { question: "Copy set bits in a range", link: "https://www.geeksforgeeks.org/copy-set-bits-in-a-range/" },
                    { question: "Divide two integers without using multiplication, division and mod operator", link: "https://www.geeksforgeeks.org/divide-two-integers-without-using-multiplication-division-mod-operator/" },
                    { question: "Calculate square of a number without using *, / and pow()", link: "https://www.geeksforgeeks.org/calculate-square-of-a-number-without-using-and-pow/" },
                    { question: "Power Set", link: "https://www.geeksforgeeks.org/power-set/" },
                ],
            
  };

  const filteredQuestions = (questionsData[activeTopic] || [])
    .filter(q => q.question.toLowerCase().includes(searchQuery.toLowerCase()));

  const openLink = (url) => {
    window.open(url, '_blank');
  };

  return (
    <div className="dsa-container">
      <header className="dsa-header">
        <h1 className="dsa-title">DSA Practice Questions</h1>
        
        
        <div className="search-box">
          <input
            type="text"
            placeholder="Search questions..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="search-input"
          />
          <span className="search-icon">🔍</span>
        </div>
      </header>

      <div className="dsa-content">
        <aside className="topics-sidebar">
          <h3 className="sidebar-title">Topics</h3>
          <ul className="topics-list">
            {Object.keys(questionsData).map((topic) => (
              <li
                key={topic}
                className={`topic-item ${activeTopic === topic ? 'active' : ''}`}
                onClick={() => {
                  setActiveTopic(topic);
                  setSearchQuery("");
                }}
              >
                {topic}
                {activeTopic === topic && <span className="active-indicator"></span>}
              </li>
            ))}
          </ul>
        </aside>

        <main className="questions-main">
          <div className="questions-header">
            <h2 className="topic-title">{activeTopic}</h2>
            <span className="questions-count">{filteredQuestions.length} questions</span>
          </div>

          {filteredQuestions.length > 0 ? (
            <ul className="questions-list">
              {filteredQuestions.map((q, index) => (
                <li 
                  key={index} 
                  className="question-item"
                  onClick={() => openLink(q.link)}
                >
                  <span className="question-text">{q.question}</span>
                  <span className="external-link">↗</span>
                </li>
              ))}
            </ul>
          ) : (
            <div className="no-results">
              <p>No questions found matching your search.</p>
              <button 
                className="clear-search"
                onClick={() => setSearchQuery("")}
              >
                Clear search
              </button>
            </div>
          )}
        </main>
      </div>
    </div>
  );
};

export default DSAPractice;